### ISSUE TITLE
Unable to install on hassbian, misconfigured dependency?

### ISSUE THREAD

**Issue by PLANETaXis** [Spartan-II-117/node-red-contrib-home-assistant-llat#40]
Hi, I'm unable to install either this or the original package from node-red "Manage Packages" or from the command line "npm install node-red-contrib-home-assistant-llat" fails with the same error:

> pi@hassbian:~/.node-red $ npm install node-red-contrib-home-assistant-llat
> (node:8748) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
> npm ERR! git clone git@github.com:github:node-red/node-red Cloning into bare repository '/home/pi/.npm/_git-remotes/git-github-com-github-node-red-node-red-b505ab45'...
> npm ERR! git clone git@github.com:github:node-red/node-red Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
> npm ERR! git clone git@github.com:github:node-red/node-red Permission denied (publickey).
> npm ERR! git clone git@github.com:github:node-red/node-red fatal: Could not read from remote repository.
> npm ERR! git clone git@github.com:github:node-red/node-red
> npm ERR! git clone git@github.com:github:node-red/node-red Please make sure you have the correct access rights
> npm ERR! git clone git@github.com:github:node-red/node-red and the repository exists.
> npm ERR! notarget No compatible version found: node-red@'github:node-red/node-red#0.18.2'
> npm ERR! notarget Valid install targets:
> npm ERR! notarget ["0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.8.0","0.8.1","0.9.0","0.9.1","0.9.1-nocolors","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.10.6","0.10.8","0.10.8-2","0.10.8-3","0.10.9","0.10.10","0.11.0","0.11.1","0.11.2","0.12.0","0.12.1","0.12.2","0.12.3","0.12.4","0.12.5","0.13.0","0.13.1","0.13.2","0.13.3","0.13.4","0.14.0","0.14.1","0.14.2","0.14.3","0.14.4","0.14.5","0.14.6","0.15.0","0.15.1","0.15.2","0.15.3","0.16.0","0.16.1","0.16.2","0.17.0","0.17.2","0.17.3","0.17.4","0.17.5","0.18.0","0.18.1","0.18.2","0.18.3","0.18.4","0.18.5","0.18.6","0.18.7","0.19.0","0.19.1","0.19.2","0.19.3","0.19.4"]
> npm ERR! notarget
> npm ERR! notarget This is most likely not a problem with npm itself.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! System Linux 4.14.70-v7+
> npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-home-assistant-llat"
> npm ERR! cwd /home/pi/.node-red
> npm ERR! node -v v8.11.1
> npm ERR! npm -v 1.4.21
> npm ERR! code ETARGET

This thread [here](https://github.com/node-red/node-red/issues/1885#issuecomment-420207961) says the issue is due to the dependency line 
`"node-red": "node-red/node-red#0.18.2" `
in package.json

Using node-red version 0.19.3, installed on hassbian.

**Comment by Spartan-II-117** [comment]
go ahead and submit a PR against dev-master for this change and i'll give it a test. if i have time before you get to it I'll do it myself.

**Comment by joseska** [comment]
same error here....

**Comment by gdselzer** [comment]
Same issue.

Node-RED version: v0.19.3
npm version: 1.4.21
hassbian

**Comment by Spartan-II-117** [comment]
I've pushed a potential fix to dev-master, I won't have time to test it until tomorrow, but if everything is sanguine I'll push a new version to NPM

**Comment by Spartan-II-117** [comment]
0.3.8 is now live on NPM and will hopefully fix this issue, can someone verify?

**Comment by Spartan-II-117** [comment]
if this is still an issue, please re-open the issue

**Comment by PLANETaXis** [comment]
Thanks for the update but no luck unfortunately, although it may be a separate issue.  I'm unable to re-open this, can you please re-open or start a new issue?

I did a cache clean and then tried reinstalling with "npm install node-red-contrib-home-assistant-llat", received the following errors:

> npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/node-home-assistant-llat/node_modules/pino/node_modules/fast-safe-stringify'
> npm ERR! error rolling back  node-home-assistant-llat@0.2.4 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/node-home-assistant-llat/node_modules/pino/node_modules/fast-safe-stringify'
> npm ERR! error rolling back   errno: -39,
> npm ERR! error rolling back   code: 'ENOTEMPTY',
> npm ERR! error rolling back   syscall: 'rmdir',
> npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/node-home-assistant-llat/node_modules/pino/node_modules/fast-safe-stringify' }
> npm ERR! tar.unpack untar error /home/pi/.npm/chrono-node/1.3.5/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/node-emoji/1.8.1/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/cardinal/1.0.0/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/cli-table/0.3.1/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/readable-stream/1.0.34/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/ansi-regex/4.0.0/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/ansi-regex/2.1.1/package.tgz
> npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/lowdb/node_modules/lodash/fp'
> npm ERR! error rolling back  node-red-contrib-home-assistant-llat@0.3.10 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/lowdb/node_modules/lodash/fp'
> npm ERR! error rolling back   errno: -39,
> npm ERR! error rolling back   code: 'ENOTEMPTY',
> npm ERR! error rolling back   syscall: 'rmdir',
> npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/lowdb/node_modules/lodash/fp' }
> npm ERR! Error: Method Not Allowed
> npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
> npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
> npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
> npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
> npm ERR! If you need help, you may report this *entire* log,
> npm ERR! including the npm and node versions, at:
> npm ERR!     <http://github.com/npm/npm/issues>
> 
> npm ERR! System Linux 4.14.70-v7+
> npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-home-assistant-llat"
> npm ERR! cwd /home/pi/.node-red
> npm ERR! node -v v8.11.1
> npm ERR! npm -v 1.4.21
> npm ERR! code E405
> npm ERR! tar.unpack untar error /home/pi/.npm/pino-std-serializers/2.2.1/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/yargs/12.0.2/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/debug/3.1.0/package.tgz
> npm ERR! tar.unpack untar error /home/pi/.npm/babel-core/6.26.3/package.tgz
> npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/node-home-assistant-llat/node_modules/blessed-contrib/node_modules/sparkline/node_modules/nopt'
> npm ERR! error rolling back  blessed-contrib@4.8.7 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/node-home-assistant-llat/node_modules/blessed-contrib/node_modules/sparkline/node_modules/nopt'
> npm ERR! error rolling back   errno: -39,
> npm ERR! error rolling back   code: 'ENOTEMPTY',
> npm ERR! error rolling back   syscall: 'rmdir',
> npm ERR! error rolling back   path: '/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat/node_modules/node-home-assistant-llat/node_modules/blessed-contrib/node_modules/sparkline/node_modules/nopt' }
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/pi/.node-red/npm-debug.log
> npm ERR! not ok code 0


Hidden amongst all of the rollbacks seems to be this:

> npm ERR! Error: Method Not Allowed
> npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
> npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
> npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
> npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
>

**Comment by joseska** [comment]
Similar to PLANETaXis
Same error or very similar

**Comment by Spartan-II-117** [comment]
can you try deleting the folder home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat and installing again?

**Comment by PLANETaXis** [comment]
Yep tried that.  I initially got a lot more errors, so found and deleted every reference to node-red-contrib-home-assistant and node-red-contrib-home-assistant-llat, and also did a npm cache clean.

The errors above are from a "clean" install.

**Comment by joseska** [comment]
same here.... 
home/pi/.node-red/node_modules/node-red-contrib-home-assistant-llat remove and same error....

Node-Red 0.19.3 on Raspbian (Google Voice Kit SD image)
Node v8.11.1
npm 1.4.21

Thanks for your support

**Comment by joseska** [comment]
ok...... I think that now is worked. I try this and I think is correct:


(https://stackoverflow.com/questions/48359107/unable-to-update-nodejs-and-npm-on-raspbian-raspberry-pi-3)
sudo su -
apt-get remove nodered -y
apt-get remove nodejs nodejs-legacy -y
apt-get remove npm  -y



(https://github.com/nodesource/distributions)
curl -sL https://deb.nodesource.com/setup_10.x | bash -
apt-get install -y nodejs



(https://nodered.org/docs/hardware/raspberrypi)
bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)

I hope that this can help you....

**Comment by Spartan-II-117** [comment]
@joseska does this now work for you?

**Comment by joseska** [comment]
yes, now is working
Nodejs 10.11.0
npm 6.4.1
node-red 0.19.4
![si](https://user-images.githubusercontent.com/7722479/46722417-54bd6500-cc6d-11e8-8e1b-89ce328008f2.jpg)

Thanks for your support
